runtime: nodejs20
handlers:
  - url: /images
    static_dir: build/images
  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|webp|svg|woff|woff2|ttf|eot))
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg|webp|svg|woff|woff2|ttf|eot)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
